### ISSUE TITLE
Number Format Exception when re-ordering by column in observation list

### ISSUE THREAD

**Issue by dbenn** [AAVSO/VStar#11]
NatisTheGreek in a CHOICE course reports "Getting an exception when selecting any column..."

See https://www.aavso.org/comment/70311#comment-70311

<img width="637" alt="image" src="https://user-images.githubusercontent.com/4115628/82140776-5222e880-9870-11ea-827f-ba8e29717207.png">

This would appear to be a localisation issue as used by the column sorter.

**Comment by dbenn** [comment]
I can reproduce this by setting my locale prefs to German, for example. The File -> Log entry is:
~~~
Mai 17, 2020 7:15:54 PM org.aavso.tools.vstar.ui.dialog.MessageBox showErrorDialog
SCHWERWIEGEND: Error
java.lang.NumberFormatException: For input string: "2447003,6"
	at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2043)
	at sun.misc.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
	at java.lang.Double.parseDouble(Double.java:538)
	at org.aavso.tools.vstar.util.comparator.DoubleAsStringComparator.compare(Unknown Source)
	at org.aavso.tools.vstar.util.comparator.DoubleAsStringComparator.compare(Unknown Source)
...
~~~

**Comment by dbenn** [comment]
This can be fixed by using `NumberParser.parseDouble()` which uses VeLa.

**Comment by dbenn** [comment]
I suspect this is only a problem for numeric columns, not string columns.

**Comment by dbenn** [comment]
Tested
