### ISSUE TITLE
WWZ plot range length error

### ISSUE THREAD

**Issue by dbenn** [AAVSO/VStar#390]
This issue was reported via the VStar forum: https://www.aavso.org/wwz-error

Steps to repeat:
- Load this simple (2 column) data file: [data.zip](https://github.com/AAVSO/VStar/files/13793432/data.zip)
- Create a filter from the left hand segment of data < 2010
- Perform WWZ with Period: min: 10, max: 13, period step:  0.1, decay: 0.01, time divisions: 50
  - The initial report was for WWZ with Frequency but the above yields the error as well
- Dismiss the error dialog that opens with error: A positive range length is required: Range[12.0,12.0]
- Select File -> Log... giving:
~~~
Dec 29, 2023 10:07:54 PM org.aavso.tools.vstar.ui.dialog.MessageBox showErrorDialog
SEVERE: Error
java.lang.IllegalArgumentException: A positive range length is required: Range[12.0,12.0]
	at org.jfree.chart.axis.ValueAxis.setRange(ValueAxis.java:1278)
	at org.jfree.chart.axis.ValueAxis.setRange(ValueAxis.java:1256)
	at org.aavso.tools.vstar.ui.dialog.period.wwz.WWZPlotPane.configureChart(Unknown Source)
	at org.aavso.tools.vstar.ui.dialog.period.wwz.WWZPlotPane.<init>(Unknown Source)
	at org.aavso.tools.vstar.ui.dialog.period.wwz.WeightedWaveletZTransformResultDialog.createChart(Unknown Source)
	at org.aavso.tools.vstar.ui.dialog.period.wwz.WeightedWaveletZTransformResultDialog.createTabs(Unknown Source)
	at org.aavso.tools.vstar.ui.dialog.period.wwz.WeightedWaveletZTransformResultDialog.createContent(Unknown Source)
	at org.aavso.tools.vstar.plugin.period.PeriodAnalysisDialogBase.prepareDialog(Unknown Source)
	at org.aavso.tools.vstar.ui.dialog.period.wwz.WeightedWaveletZTransformResultDialog.<init>(Unknown Source)
	at org.aavso.tools.vstar.plugin.period.impl.WeightedWaveletZTransformWithPeriodRangePlugin.getDialog(Unknown Source)
	at org.aavso.tools.vstar.ui.task.PeriodAnalysisTask.done(Unknown Source)
	at java.desktop/javax.swing.SwingWorker$5.run(SwingWorker.java:750)
	at java.desktop/javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.run(SwingWorker.java:848)
	at java.desktop/sun.swing.AccumulativeRunnable.run(AccumulativeRunnable.java:112)
	at java.desktop/javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.actionPerformed(SwingWorker.java:858)
	at java.desktop/javax.swing.Timer.fireActionPerformed(Timer.java:311)
	at java.desktop/javax.swing.Timer$DoPostEvent.run(Timer.java:243)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:771)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:741)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
~~~

**Comment by dbenn** [comment]
Observations:
- From the exception trace, the WWZ algorithm itself completes and the error is happening during WWZ result plot creation.
- If the (few) observations with brightness < 0.07 are excluded from the filter, the error does not occur!
