### ISSUE TITLE
ObservationDetails dialog is sometimes not shown

### ISSUE THREAD

**Issue by mpyat2** [AAVSO/VStar#455]
After creating user-defined series from filtered ones, the ObservationDetails dialog is sometimes not shown in the PhasePlot mode.

If the command is invoked from the menu, the following error is shown:
![image](https://github.com/user-attachments/assets/18d65380-8158-420b-b355-65fc3756fd7d)

If the command is invoked with the taskbar button, no error is displayed, and no dialog is shown. An exception is logged:
Oct 25, 2024 4:26:13 PM org.aavso.tools.vstar.ui.dialog.MessageBox showErrorDialog
SEVERE: Error
java.lang.NullPointerException
	at org.aavso.tools.vstar.ui.dialog.series.MeanSourcePane.checkInitialMeanSourceSeries(MeanSourcePane.java:237)
	at org.aavso.tools.vstar.ui.dialog.series.MeanSourcePane.createDerivedSeriesRadioButtons(MeanSourcePane.java:143)
	at org.aavso.tools.vstar.ui.dialog.series.MeanSourcePane.addSeriesRadioButtons(MeanSourcePane.java:93)
	at org.aavso.tools.vstar.ui.dialog.series.MeanSourcePane.<init>(MeanSourcePane.java:81)
	at org.aavso.tools.vstar.ui.dialog.PlotControlDialog.createSeriesChangePane(PlotControlDialog.java:255)
	at org.aavso.tools.vstar.ui.dialog.PlotControlDialog.createChartControlPanel(PlotControlDialog.java:163)
	at org.aavso.tools.vstar.ui.dialog.PlotControlDialog.createContent(PlotControlDialog.java:138)
	at org.aavso.tools.vstar.ui.dialog.PlotControlDialog.<init>(PlotControlDialog.java:118)
	at org.aavso.tools.vstar.ui.mediator.Mediator.showPlotControlDialog(Mediator.java:1758)
	at org.aavso.tools.vstar.ui.MenuBar$16.actionPerformed(MenuBar.java:904)
	at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
	at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
	at java.awt.AWTEventMulticaster.mouseReleased(Unknown Source)
	at java.awt.Component.processMouseEvent(Unknown Source)
	at javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.awt.Component.processEvent(Unknown Source)
	at java.awt.Container.processEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)

the exact combination of operations causing the error is still not determined.

**Comment by dbenn** [comment]
I have tried to reproduce this but not been able to so far @mpyat2.

Is it deterministic? If so, can you provide how-to-reproduce steps based on the example above or similar?

**Comment by mpyat2** [comment]
Hi @dbenn 
Unfortunately, I cannot find a deterministic way now. I created this issue because it does exist, yet I need additional investigations. I will try and add additional information when find it.
